FROM node:lts AS runtime
WORKDIR /app

COPY apps/web /app

RUN yarn install
RUN yarn add -D @pandacss/dev
RUN yarn prepare
RUN yarn build

ENV HOST=0.0.0.0
ENV PORT=4321
EXPOSE 4321
CMD node ./dist/server/entry.mjs
